"""Alert explainer.

Mirror of explainer.py but for MonitorAlert rows.

Two execution paths:

  1. Alert is linked to a Finding (alert.finding_id set):
     The finding-explainer is the source of truth — we delegate to it and
     prepend a small "Why this alert fired" preamble that uses alert-only
     fields (alert_type, change context, when).

  2. Alert is NOT linked to a finding (manual / lookup_tool / change without
     a persisted finding):
     We synthesise the 5-section payload from the alert's own fields plus a
     category-based fallback keyed on `source` and `alert_type`.

Both paths return the same shape as explain_finding() so the same frontend
component can render either.
"""
from __future__ import annotations

from .explainer import explain_finding


# ---------------------------------------------------------------------------
# Per-source/per-alert-type fallback library
# ---------------------------------------------------------------------------

_SOURCE_DESCRIPTIONS = {
    "lookup_tool": (
        "This alert was saved manually from a Lookup Tool result. "
        "It captures a point-in-time snapshot of what the tool reported "
        "against the target — treat it as analyst-curated rather than "
        "scheduled-monitoring output."
    ),
    "finding": (
        "This alert was escalated from a finding so it routes through your "
        "notification rules (Slack, Jira, email)."
    ),
    "manual": (
        "This alert was created manually by an analyst, not by an automated "
        "monitor. Severity and triage are at the analyst's discretion."
    ),
    "monitor": (
        "This alert was generated by a continuous monitor checking for "
        "changes on the target. Each cycle compares the latest scan output "
        "against the established baseline; differences become alerts."
    ),
}

_ALERT_TYPE_DESCRIPTIONS = {
    "new_finding": (
        "A new issue was detected that wasn't present in the prior scan baseline. "
        "Investigate whether the issue was introduced recently and whether "
        "other assets share the same exposure."
    ),
    "severity_change": (
        "An existing finding's severity changed compared to the previous "
        "scan — typically because a new CVE was disclosed, a misconfiguration "
        "got worse, or a workaround was reverted."
    ),
    "resolved": (
        "A previously open finding is no longer detected. This is usually "
        "good news, but verify the fix actually addressed the root cause "
        "rather than just changing the scanner's view of the asset."
    ),
    "manual": (
        "This is a manually-created alert, not an automated detection. "
        "The summary and severity were set by the creator."
    ),
}


def _why_fired(alert) -> str:
    """One-liner explaining what triggered this alert, used as a header
    line in the technical explanation when we have a linked finding."""
    bits = []

    src = (alert.source or "monitor").lower()
    if src == "monitor":
        atype = (alert.alert_type or "").lower()
        if atype == "new_finding":
            bits.append("A scheduled monitor detected a new finding that wasn't present in the prior baseline.")
        elif atype == "severity_change":
            bits.append("A scheduled monitor detected that an existing finding's severity changed.")
        elif atype == "resolved":
            bits.append("A scheduled monitor detected that a previously open finding is no longer present.")
        else:
            bits.append("A scheduled monitor flagged a change on the target.")
    elif src == "lookup_tool":
        tool = (alert.source_tool or "lookup tool").replace("_", " ")
        target = alert.source_target or alert.asset_value or "the target"
        bits.append(f"An analyst saved this from the {tool} tool while inspecting {target}.")
    elif src == "finding":
        bits.append("This alert was manually escalated from an existing finding so it routes through your notification rules.")
    elif src == "manual":
        bits.append("An analyst created this alert manually — it is not the output of an automated monitor.")

    if alert.created_at:
        bits.append(f"Fired at {alert.created_at.strftime('%Y-%m-%d %H:%M UTC')}.")

    return " ".join(bits)


def _alert_evidence(alert) -> str:
    """Render the alert's metadata as a multi-line evidence block. Used for
    the no-finding path."""
    lines: list[str] = []

    if alert.asset_value:
        lines.append(f"Asset: {alert.asset_value}")
    if alert.group_name:
        lines.append(f"Group: {alert.group_name}")
    if alert.source:
        src_label = alert.source.replace("_", " ").title()
        if alert.source_tool:
            tool = alert.source_tool.replace("_", " ").title()
            lines.append(f"Source: {src_label} · {tool}")
        else:
            lines.append(f"Source: {src_label}")
    if alert.source_target:
        lines.append(f"Source target: {alert.source_target}")
    if alert.alert_type and alert.alert_type != "manual":
        lines.append(f"Alert type: {alert.alert_type.replace('_', ' ')}")
    if alert.created_at:
        lines.append(f"Fired: {alert.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if alert.acknowledged_at:
        lines.append(f"Acknowledged: {alert.acknowledged_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if alert.notified_via:
        channels = ", ".join(alert.notified_via) if isinstance(alert.notified_via, list) else str(alert.notified_via)
        lines.append(f"Notified via: {channels}")

    if not lines:
        return "No structured metadata captured for this alert beyond its title."

    return "\n".join(f"• {line}" for line in lines)


def _explain_standalone(alert) -> dict:
    """Build the 5-section payload for an alert that ISN'T linked to a finding."""
    src = (alert.source or "monitor").lower()
    atype = (alert.alert_type or "").lower()

    src_desc = _SOURCE_DESCRIPTIONS.get(src, _SOURCE_DESCRIPTIONS["monitor"])
    type_desc = _ALERT_TYPE_DESCRIPTIONS.get(atype) or ""

    # Summary — short and direct
    summary = alert.summary or alert.title or "Alert generated by Nano EASM monitoring."

    # Technical — explain the alert mechanism + provided summary
    technical_parts = [_why_fired(alert), src_desc]
    if type_desc:
        technical_parts.append(type_desc)
    if alert.summary and alert.summary != summary:
        technical_parts.append(f"Reported context: {alert.summary}")
    technical = "\n\n".join(p.strip() for p in technical_parts if p)

    evidence = _alert_evidence(alert)

    # Remediation — generic guidance because we don't have finding-level detail
    if src == "lookup_tool":
        remediation = (
            "Re-run the same Lookup Tool against the asset to verify the issue is "
            "still present, then act on the underlying problem if confirmed. "
            "If the alert was saved as a record-keeping artefact, mark it as "
            "resolved or suppressed."
        )
    elif atype == "resolved":
        remediation = (
            "No action typically required — confirm the fix is durable rather than "
            "a transient change in scanner output. Resolve the alert when satisfied."
        )
    elif atype == "severity_change":
        remediation = (
            "Investigate why the severity moved. If it's an upgrade, treat the "
            "underlying finding with renewed urgency. If it's a downgrade, verify "
            "the original risk is genuinely lower and not just hidden."
        )
    elif atype == "new_finding":
        remediation = (
            "Treat this as a freshly-discovered issue. Review the underlying "
            "finding (if linked), confirm scope, and apply the standard remediation "
            "flow for its category."
        )
    else:
        remediation = (
            "Review the alert details, confirm whether the underlying issue "
            "still exists, and resolve or suppress accordingly. If this alert "
            "is informational only, mark it as resolved."
        )

    # Client-friendly summary — non-technical
    client_summary = (
        f"{alert.title}. " if alert.title else ""
    ) + (
        "An automated check flagged this for review; the team should investigate "
        "and confirm whether action is required."
    )

    return {
        "summary": summary.strip(),
        "technicalExplanation": technical.strip(),
        "evidence": evidence.strip(),
        "remediation": remediation.strip(),
        "clientSummary": client_summary.strip(),
    }


# ---------------------------------------------------------------------------
# Public entrypoint
# ---------------------------------------------------------------------------

def explain_alert(alert) -> dict:
    """
    Build the 5-section explanation payload for a MonitorAlert row.

    Delegates to explain_finding() when the alert is linked to a finding
    (because the finding template registry has by far the richest content).
    Otherwise synthesises a per-source/per-alert-type explanation from
    the alert's own fields.
    """
    finding = getattr(alert, "finding", None)
    if finding is not None:
        # Linked-finding path: use the rich finding explanation, then prefix
        # the technical section with a sentence about why THIS alert fired.
        explanation = explain_finding(finding)

        why = _why_fired(alert)
        if why:
            explanation = dict(explanation)  # copy so we don't mutate the original
            existing_tech = explanation.get("technicalExplanation", "")
            explanation["technicalExplanation"] = (
                f"Why this alert fired: {why}\n\n{existing_tech}"
            ).strip()
        return explanation

    # Standalone path
    return _explain_standalone(alert)
