"""Add scan profiles and scheduling

Revision ID: 029c573fe4a1
Revises: 
Create Date: 2026-02-08 11:10:11.106058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029c573fe4a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create scan_profile table
    op.create_table('scan_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('use_shodan', sa.Boolean(), nullable=False),
    sa.Column('use_nmap', sa.Boolean(), nullable=False),
    sa.Column('use_nuclei', sa.Boolean(), nullable=False),
    sa.Column('use_sslyze', sa.Boolean(), nullable=False),
    sa.Column('shodan_include_history', sa.Boolean(), nullable=False),
    sa.Column('shodan_include_cves', sa.Boolean(), nullable=False),
    sa.Column('shodan_include_dns', sa.Boolean(), nullable=False),
    sa.Column('nmap_scan_type', sa.String(length=20), nullable=True),
    sa.Column('nmap_port_range', sa.String(length=50), nullable=True),
    sa.Column('nuclei_severity_filter', sa.String(length=100), nullable=True),
    sa.Column('nuclei_templates', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_scan_profile_org_name')
    )
    
    # Create scan_schedule table
    op.create_table('scan_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_scan_job_id'], ['scan_job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['scan_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_schedule_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_schedule_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_schedule_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_schedule_user_id'), ['user_id'], unique=False)
    
    # Create scan_historical_data table
    op.create_table('scan_historical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_historical_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_historical_data_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_historical_data_scan_job_id'), ['scan_job_id'], unique=False)
    
    # Create organization_usage table
    op.create_table('organization_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('quick_scans_count', sa.Integer(), nullable=False),
    sa.Column('standard_scans_count', sa.Integer(), nullable=False),
    sa.Column('deep_scans_count', sa.Integer(), nullable=False),
    sa.Column('total_scans_count', sa.Integer(), nullable=False),
    sa.Column('shodan_queries_used', sa.Integer(), nullable=False),
    sa.Column('active_schedules', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'month', name='uq_org_usage_month')
    )
    with op.batch_alter_table('organization_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_usage_organization_id'), ['organization_id'], unique=False)
    
    # Add new columns to scan_job table
    with op.batch_alter_table('scan_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scan_engines', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_scan_job_profile_id', 'scan_profile', ['profile_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_scan_job_schedule_id', 'scan_schedule', ['schedule_id'], ['id'], ondelete='SET NULL')
    
    # ✅ Seed default system profiles
    op.execute("""
        INSERT INTO scan_profile (
            organization_id, user_id, name, description, is_system, is_default,
            use_shodan, use_nmap, use_nuclei, use_sslyze,
            shodan_include_history, shodan_include_cves, shodan_include_dns,
            timeout_seconds, created_at, updated_at
        ) VALUES 
        -- Quick Scan (Default)
        (NULL, NULL, 'Quick Scan', 'Fast Shodan host lookup - basic information only', 
         1, 1, 1, 0, 0, 0, 0, 0, 0, 60, datetime('now'), datetime('now')),
        -- Standard Scan
        (NULL, NULL, 'Standard Scan', 'Shodan with historical data and CVE information',
         1, 0, 1, 0, 0, 0, 1, 1, 0, 120, datetime('now'), datetime('now')),
        -- Deep Scan
        (NULL, NULL, 'Deep Scan', 'Comprehensive scan with all engines',
         1, 0, 1, 0, 0, 0, 1, 1, 1, 300, datetime('now'), datetime('now'));
    """)
    
    # Update Deep Scan to enable all engines
    op.execute("""
        UPDATE scan_profile 
        SET use_nmap = 1, use_nuclei = 1, use_sslyze = 1,
            nmap_port_range = '1-65535', nuclei_severity_filter = 'critical,high,medium'
        WHERE name = 'Deep Scan' AND is_system = 1;
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove seed data
    op.execute("DELETE FROM scan_profile WHERE is_system = 1;")
    
    # Remove columns from scan_job
    with op.batch_alter_table('scan_job', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scan_job_schedule_id', type_='foreignkey')
        batch_op.drop_constraint('fk_scan_job_profile_id', type_='foreignkey')
        batch_op.drop_column('scan_engines')
        batch_op.drop_column('schedule_id')
        batch_op.drop_column('profile_id')
    
    # Drop tables in reverse order
    with op.batch_alter_table('organization_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_usage_organization_id'))
    op.drop_table('organization_usage')
    
    with op.batch_alter_table('scan_historical_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_historical_data_scan_job_id'))
        batch_op.drop_index(batch_op.f('ix_scan_historical_data_asset_id'))
    op.drop_table('scan_historical_data')
    
    with op.batch_alter_table('scan_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_schedule_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_schedule_profile_id'))
        batch_op.drop_index(batch_op.f('ix_scan_schedule_organization_id'))
        batch_op.drop_index(batch_op.f('ix_scan_schedule_asset_id'))
    op.drop_table('scan_schedule')
    
    op.drop_table('scan_profile')
    
    # ### end Alembic commands ###