"""make scan_schedule.asset_id nullable

Revision ID: 9daae445a56c
Revises: b3daa8aa9caa
Create Date: 2026-02-19 09:00:14.436209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9daae445a56c'
down_revision = 'b3daa8aa9caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_discovered_asset')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('target_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('target_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('target_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_audit_log_category'))
        batch_op.drop_index(batch_op.f('idx_audit_log_org_created'))
        batch_op.drop_index(batch_op.f('idx_audit_log_org_id'))
        batch_op.drop_index(batch_op.f('idx_audit_log_target'))
        batch_op.drop_index(batch_op.f('idx_audit_log_user'))
        batch_op.create_index(batch_op.f('ix_audit_log_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('discovered_asset', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('discovery_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_schedule_org_id'))

    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.alter_column('ignored',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('ignored_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('in_progress_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('accepted_risk_justification',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_finding_assigned_to'))
        batch_op.drop_index(batch_op.f('idx_finding_status'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['accepted_risk_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['in_progress_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['ignored_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['resolved_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('assigned_by')
        batch_op.drop_column('accepted_risk_reason')
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('finding_comment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_finding_comment_finding'))
        batch_op.drop_index(batch_op.f('idx_finding_comment_org'))
        batch_op.create_index(batch_op.f('ix_finding_comment_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_comment_organization_id'), ['organization_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'finding', ['finding_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('finding_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_finding_event_event_type'))

    with op.batch_alter_table('ignored_discovered_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ignored_discovered_asset_org_id'))

    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_index(batch_op.f('ix_integration_type'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('trigger_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_notification_rule_event_type'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'integration', ['integration_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scan_historical_data', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_scan_historical_data_asset_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'asset', ['asset_id'], ['id'])

    with op.batch_alter_table('scan_job', schema=None) as batch_op:
        batch_op.alter_column('scan_engines',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'scan_profile', ['profile_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'scan_schedule', ['schedule_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scan_schedule', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_schedule', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('scan_job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('scan_engines',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('scan_historical_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'asset', ['asset_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_scan_historical_data_asset_id'), ['asset_id'], unique=False)
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'integration', ['integration_id'], ['id'])
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_notification_rule_event_type'), ['event_type'], unique=False)
        batch_op.alter_column('trigger_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_integration_type'), ['integration_type'], unique=False)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ignored_discovered_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ignored_discovered_asset_org_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('finding_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_event_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('finding_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'finding', ['finding_id'], ['id'])
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_finding_comment_organization_id'))
        batch_op.drop_index(batch_op.f('ix_finding_comment_finding_id'))
        batch_op.create_index(batch_op.f('idx_finding_comment_org'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_finding_comment_finding'), ['finding_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'"), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('accepted_risk_reason', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('assigned_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['in_progress_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['accepted_risk_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['resolved_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['assigned_by'], ['id'])
        batch_op.create_index(batch_op.f('idx_finding_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_finding_assigned_to'), ['assigned_to'], unique=False)
        batch_op.alter_column('accepted_risk_justification',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('in_progress_notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ignored_reason',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('ignored',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('discovery_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_schedule_org_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('discovered_asset', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_organization_id'))
        batch_op.create_index(batch_op.f('idx_audit_log_user'), ['organization_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_log_target'), ['organization_id', 'target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_log_org_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_log_org_created'), ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_log_category'), ['organization_id', 'category'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('metadata_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('target_label',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('target_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('target_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_discovered_asset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('value', sa.VARCHAR(length=500), nullable=False),
    sa.Column('original_value', sa.VARCHAR(length=500), nullable=True),
    sa.Column('sources', sqlite.JSON(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), nullable=False),
    sa.Column('added_to_inventory', sa.BOOLEAN(), nullable=False),
    sa.Column('added_asset_id', sa.INTEGER(), nullable=True),
    sa.Column('discovered_at', sa.DATETIME(), nullable=False),
    sa.Column('tags', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.ForeignKeyConstraint(['added_asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['discovery_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'asset_type', 'value', name=op.f('uq_discovered_asset_job_type_value'))
    )
    # ### end Alembic commands ###
