"""agent_platform_phase1

Revision ID: e903d172a1a7
Revises: n2d3e4f5a6b7
Create Date: 2026-05-11 11:27:55.930172

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e903d172a1a7'
down_revision = 'n2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), server_default=sa.text('1.00'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['agent_memory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'key', name='uq_agent_memory_agent_key')
    )
    with op.batch_alter_table('agent_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_memory_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_memory_expires_at'), ['expires_at'], unique=False)

    op.create_table('agent_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('agent_owner', sa.String(length=64), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_thread',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_thread_agent_id'), ['agent_id'], unique=False)

    op.create_table('team_memory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('agent_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_message_thread_id'), ['thread_id'], unique=False)

    op.create_table('agent_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_agent_id'), ['agent_id'], unique=False)

    op.create_table('pending_action',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_action_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_action_agent_id'), ['agent_id'], unique=False)

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), server_default=sa.text("'customer'"), nullable=False))
        batch_op.create_index(batch_op.f('ix_api_key_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_kind'))
        batch_op.drop_column('kind')

    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_action_agent_id'))
        batch_op.drop_index(batch_op.f('ix_pending_action_action_type'))

    op.drop_table('pending_action')
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_agent_id'))

    op.drop_table('agent_run')
    with op.batch_alter_table('agent_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_message_thread_id'))

    op.drop_table('agent_message')
    op.drop_table('team_memory')
    with op.batch_alter_table('agent_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_thread_agent_id'))

    op.drop_table('agent_thread')
    op.drop_table('agent_task')
    with op.batch_alter_table('agent_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_memory_expires_at'))
        batch_op.drop_index(batch_op.f('ix_agent_memory_agent_id'))

    op.drop_table('agent_memory')
    # ### end Alembic commands ###
