# migrations/versions/m8_monitoring_tables.py
"""
M8: Add monitoring system tables.

Creates:
    - monitor            — Tracks monitored assets/groups with scheduling
    - monitor_alert      — Alerts generated by change detection
    - monitor_settings   — Org-level notification preferences
    - tuning_rule        — Rules to suppress/downgrade/upgrade/snooze alerts

Run with: flask db upgrade

Depends on: m7_finding_cols (Finding model must have template_id column)
"""

from alembic import op
import sqlalchemy as sa


# Revision identifiers
revision = "m8_monitoring"
down_revision = "a64ffb4308db"  # add_group_schedule_support
branch_labels = None
depends_on = None


def upgrade():
    # Use bind to check which tables already exist (db.create_all may have run)
    conn = op.get_bind()
    existing = set(sa.inspect(conn).get_table_names())

    # ── monitor ───────────────────────────────────────────────────────
    if "monitor" not in existing:
        op.create_table(
            "monitor",
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("organization_id", sa.Integer, sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False, index=True),
            sa.Column("created_by", sa.Integer, sa.ForeignKey("user.id", ondelete="SET NULL"), nullable=True),

            # Target
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("asset.id", ondelete="CASCADE"), nullable=True, index=True),
            sa.Column("group_id", sa.Integer, sa.ForeignKey("asset_group.id", ondelete="CASCADE"), nullable=True, index=True),

            # Configuration
            sa.Column("monitor_types", sa.JSON, nullable=False, server_default='["all"]'),
            sa.Column("frequency", sa.String(20), nullable=False, server_default="every_2_days"),
            sa.Column("enabled", sa.Boolean, nullable=False, server_default="1"),

            # Tracking
            sa.Column("baseline_scan_job_id", sa.Integer, sa.ForeignKey("scan_job.id", ondelete="SET NULL"), nullable=True),
            sa.Column("last_scan_job_id", sa.Integer, sa.ForeignKey("scan_job.id", ondelete="SET NULL"), nullable=True),
            sa.Column("last_checked_at", sa.DateTime, nullable=True),
            sa.Column("next_check_at", sa.DateTime, nullable=True),

            # Timestamps
            sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.func.now()),

            # Unique constraints
            sa.UniqueConstraint("organization_id", "asset_id", name="uq_monitor_org_asset"),
            sa.UniqueConstraint("organization_id", "group_id", name="uq_monitor_org_group"),
        )

    # ── monitor_alert ─────────────────────────────────────────────────
    if "monitor_alert" not in existing:
        op.create_table(
            "monitor_alert",
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("organization_id", sa.Integer, sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False, index=True),
            sa.Column("monitor_id", sa.Integer, sa.ForeignKey("monitor.id", ondelete="CASCADE"), nullable=False, index=True),
            sa.Column("finding_id", sa.Integer, sa.ForeignKey("finding.id", ondelete="SET NULL"), nullable=True, index=True),

            # Classification
            sa.Column("alert_type", sa.String(30), nullable=False),
            sa.Column("template_id", sa.String(100), nullable=True),
            sa.Column("alert_name", sa.String(255), nullable=True),

            # Content
            sa.Column("title", sa.String(255), nullable=False),
            sa.Column("summary", sa.String(1000), nullable=True),
            sa.Column("severity", sa.String(20), nullable=False, server_default="info"),

            # Context
            sa.Column("asset_value", sa.String(255), nullable=True),
            sa.Column("group_name", sa.String(255), nullable=True),

            # Status workflow
            sa.Column("status", sa.String(20), nullable=False, server_default="open", index=True),
            sa.Column("acknowledged_at", sa.DateTime, nullable=True),
            sa.Column("acknowledged_by", sa.Integer, sa.ForeignKey("user.id", ondelete="SET NULL"), nullable=True),
            sa.Column("resolved_at", sa.DateTime, nullable=True),
            sa.Column("resolved_by", sa.Integer, sa.ForeignKey("user.id", ondelete="SET NULL"), nullable=True),

            # Notification tracking
            sa.Column("notified_via", sa.JSON, nullable=True),

            # Timestamps
            sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        )

    # ── monitor_settings ──────────────────────────────────────────────
    if "monitor_settings" not in existing:
        op.create_table(
            "monitor_settings",
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("organization_id", sa.Integer, sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False, unique=True, index=True),

            # Channels
            sa.Column("email_enabled", sa.Boolean, nullable=False, server_default="1"),
            sa.Column("in_app_enabled", sa.Boolean, nullable=False, server_default="1"),
            sa.Column("webhook_enabled", sa.Boolean, nullable=False, server_default="0"),
            sa.Column("webhook_url", sa.String(500), nullable=True),
            sa.Column("email_recipients", sa.JSON, nullable=False, server_default="[]"),

            # Preferences
            sa.Column("notify_on_severity", sa.JSON, nullable=False, server_default='["critical","high","medium","low","info"]'),
            sa.Column("digest_frequency", sa.String(20), nullable=False, server_default="immediate"),

            # Timestamps
            sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        )

    # ── tuning_rule ───────────────────────────────────────────────────
    if "tuning_rule" not in existing:
        op.create_table(
            "tuning_rule",
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("organization_id", sa.Integer, sa.ForeignKey("organization.id", ondelete="CASCADE"), nullable=False, index=True),
            sa.Column("created_by", sa.Integer, sa.ForeignKey("user.id", ondelete="SET NULL"), nullable=True),
            sa.Column("enabled", sa.Boolean, nullable=False, server_default="1"),

            # Match conditions (all optional)
            sa.Column("template_id", sa.String(100), nullable=True),
            sa.Column("category", sa.String(50), nullable=True),
            sa.Column("severity_match", sa.String(20), nullable=True),
            sa.Column("asset_id", sa.Integer, sa.ForeignKey("asset.id", ondelete="CASCADE"), nullable=True),
            sa.Column("group_id", sa.Integer, sa.ForeignKey("asset_group.id", ondelete="CASCADE"), nullable=True),
            sa.Column("asset_pattern", sa.String(255), nullable=True),
            sa.Column("port", sa.Integer, nullable=True),
            sa.Column("service_name", sa.String(100), nullable=True),
            sa.Column("cwe", sa.String(20), nullable=True),
            sa.Column("title_contains", sa.String(255), nullable=True),

            # Action
            sa.Column("action", sa.String(20), nullable=False),
            sa.Column("target_severity", sa.String(20), nullable=True),
            sa.Column("snooze_until", sa.DateTime, nullable=True),

            # Metadata
            sa.Column("reason", sa.String(500), nullable=True),
            sa.Column("dedupe_key", sa.String(64), nullable=True, unique=True),

            # Timestamps
            sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
            sa.Column("updated_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        )


def downgrade():
    op.drop_table("tuning_rule")
    op.drop_table("monitor_settings")
    op.drop_table("monitor_alert")
    op.drop_table("monitor")